name: Test Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prepare-source:
    uses: './.github/workflows/prepare-source.yml'
    with:
      target_ref: '${{ github.ref_name }}'

  build:
    needs: prepare-source
    uses: './.github/workflows/build.yml'

  build-flatpak:
    needs: prepare-source
    uses: './.github/workflows/build-flatpak.yml'
    with:
      target_ref: '${{ github.ref_name }}'

  publish-gh:
    needs: [prepare-source, build, build-flatpak]
    uses: './.github/workflows/publish-gh.yml'
    with:
      target_ref: '${{ github.ref_name }}'
      variant: 'test'
